name: Continuous Integration

on:
  push:
    branches:
      - 'feature/*'
      - 'refactor/*'

jobs:

  test-typescript:

    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-test
        run: npm test

  get-branch-name:

    name: Get Branch Name
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
    outputs:
      current-branch: ${{ steps.current_branch_name.outputs.current_branch}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Branch Name
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

    - name: Display Branch Name
      run: |
        echo "Branch Name: $BRANCH_NAME "

    - name: Set Current Branch as Output Value
      id: current_branch_name
      run: echo "current_branch=$BRANCH_NAME" >> $GITHUB_ENV

  open-pr-to-develop:

    name: Open PR To Develop
    needs: 
      - test-typescript
      - get-branch-name
    uses: ./.github/workflows/pr-to-next-branch.yml
    with:
      source-branch: ${{ needs.get-branch-name.outputs.current_branch }}
      target-branch: develop

