name: Continuous Integration

on:
  push:
    branches:
      - 'feature/*'
      - 'refactor/*'

jobs:

  test-typescript:

    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-test
        run: npm test

  open-pr-to-develop:

    name: Open PR To Develop
    needs: 
      - test-typescript
    uses: ./.github/workflows/pr-to-next-branch.yml
    with:
      source-branch: ${{ github.ref_name }}
      target-branch: develop

  open-pr-to-main:

    name: Open PR To Main
    needs:
      - open-pr-to-develop
    uses: ./.github/workflows/pr-to-next-branch.yml
    with:
      source-branch: develop
      target-branch: main

